# Generated by Django 4.0 on 2022-01-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_desc',
            field=models.IntegerField(default=0),
        ),
    ]
