# Generated by Django 4.0 on 2022-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_desc',
            field=models.CharField(max_length=200),
        ),
    ]
